# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('remanage', '0003_auto_20160607_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 23, 35, 51, 976200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 23, 35, 51, 975469, tzinfo=utc)),
        ),
    ]
